### ISSUE TITLE
capture fail on card no.70

### ISSUE THREAD

**Issue by Kaiay** [MgAl2O4/FFTriadBuddy#46] opened 2021-07-01 21:56 UTC
I was playing with Idle Imperial at Azys Lla (28, 31)
while he put the card no.70 on the board or it swap to my deck, buddy will get waring. And waring continue every turn until the game is over, then happen again and again every game.
![image](https://user-images.githubusercontent.com/43386053/124193525-8c455d00-daf9-11eb-9edd-8d521af40dfe.png)
![image](https://user-images.githubusercontent.com/43386053/124193551-9c5d3c80-daf9-11eb-8318-323ca37fb400.png)

**Comment by MgAl2O4** [comment] 2021-07-01 22:08
Hm, that's a special card with side numbers not being unique. Tool is supposed to learn how it looks - that's why it's asking what card is it.

If it failed to recognize that card after saving image data, it's a bug :/
Can you send a screenshot from game showing the issue, so I can repro and fix it?

**Comment by MgAl2O4** [comment] 2021-07-11 16:13
No evidence of a bug, can't repro anything on my end, closing as by design.
If still occurs, please reopen and provide two screenshots (failed initial scan + failed scan after teaching tool which card is it)

**Closed by MgAl2O4** 2021-07-11 16:13 UTC
